### PR TITLE
Raw JSON RPC `decoderawtransaction`

### PR DESCRIPTION
**Pull request by 0x4c1d**
Partially #247 #308 
- Implemented `decoderawtransaction`.
- Add test for getrawtransaction(verbose=true) https://github.com/paritytech/parity-bitcoin/pull/551#pullrequestreview-223828261

### CODE REVIEW

**Comment by 0x4c1d** [comment]
[clabot:check]

**Comment by 0x4c1d** [comment]
Oops, for some reason, did not work CI. Maybe I recreate PR?

**Comment by svyatonik** [comment]
Yes - sorry for that - we have been refactoring and fixing CI for last month :) Could you, please, rebase/merge latest master. Thank you!

**Comment by 0x4c1d** [comment]
Strange, but it didn’t work, CI didn’t work anyway

**Pull request merged**
