### PR TITLE
Unlock rand crate version 0.3.14 -> 0.3

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by korczis** [comment]
[clabot:check]

**Comment by svyatonik** [comment]
Thanks for your help, @korczis ! Can you please also commit `Cargo.lock` after running `cargo update -p rand` to apply these changes?

**Comment by debris** [comment]
actually, latest `rand` version is `0.4`, so maybe let's update to that one instead?

**Comment by korczis** [comment]
@debris Here we go!

**Pull request closed without merging**
